### ISSUE TITLE
无法获得链接信息

### ISSUE THREAD

**Issue by donald111ms** [Misaka-blog/replit-xray#5]
点击上面的“Run”按钮，控制台只出现了下面内容：“点击以下链接，以获取节点信息：
https://don-xray.donald111.repl.co/e1be3709-03cf-4285-9437-e39239cc34d5.html
Replit 保活日志：”

我点那个链接，浏览器报“此网站无法提供安全连接 ERR_SSL_PROTOCOL_ERROR”。右边的Webview窗口一直在转圈圈。。。最后页面显示“Hmm... We couldn't reach this Repl  Make sure this Repl has a port open and is ready to receive HTTP traffic.”

希望您能看下，谢谢！

**Comment by Misaka-blog** [comment]
@donald111ms 早没了啊

**Comment by zhongzhiyuan0615** [comment]
傻逼玩意别他妈滥用了，活不起别活，给你建站用的你搭代理你贱不贱啊傻逼

**Comment by donald111ms** [comment]
我刚才把那个删除了，这个您看下：https://don111.donald111.repl.co/e1be3709-03cf-4285-9437-e39239cc34d5.html

**Comment by zhongzhiyuan0615** [comment]
你妈是不是死了，脑子有问题趁早去治，你除了滥用你还会干什么，你是活不起了吗亲妈死了没钱下葬了吗还是吃不起饭在大街上流浪呢
